version: 2.1
jobs:
  compile:
    docker:
      - image: golang
    steps:
      - checkout
      - run: git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - run: GOPRIVATE=github.com/codecomet-io go build

workflows:
  version: 2
  build_app:
    jobs:
      - compile
